<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NetCoreServer" Version="8.0.7" />
    <PackageReference Include="Steamworks.NET" Version="2024.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GoldsrcNetPackage\GoldsrcNetPackage.csproj" />
  </ItemGroup>

</Project>
